# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jing Deng
title: Software Engineer (SDE)
email: cugbjing@gmail.com
website: https://cugbjing.github.io/resume/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  cugbjing
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: jing-deng-39ab5a17
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Jing and I'm a full stack web developer with professional experience in developing Web applications, automation pipelines, and APIs supported by AWS platform, plus proficient knowledge in GIS applications.

  I have worked with various programming languages and frameworks and I am passionate about learning something new. The things that I currently have the most experience working with are: 
  <mark>Python</mark>, <mark>JavaScript</mark>, <mark>RESTfull</mark>, <mark>AWS</mark>, <mark>Firebase</mark>, <mark>SQL</mark>, <mark>React/Redux</mark>, <mark>Node JS</mark>, <mark>Material UI</mark>, <mark>HTML</mark>, <mark>CSS</mark>, <mark>ArcGIS</mark>, <mark>OpenLayers</mark>, <mark>Geoserver</mark>, <mark>PostgreSQL</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AWS
        link: aws.amazon.com
        # link_text: aws.com
        sub_title: SDE2
        caption: Dec 2021 - Present
        quote: >
          Work hard, have fun, make history
        description: | # this will include new lines to allow paragraphs
          - Improve the livestreaming platform for internal Amazon emphasizing on scalability, availability and security

      - layout: left
        title: Bayer
        link: bayer.com
        sub_title: Full Stack Web Developer 
        caption: 2020 - Dec 2021
        quote: >
          Science for a better life
        description: | # this will include new lines to allow paragraphs
          - Developed web apps of Geospatial data visualization and data analysis using <Mark>JavaScript</Mark>, <Mark>MongoDB</Mark>, <Mark>Node</Mark>, <Mark>Kafka</Mark>, <Mark>Material UI</Mark>, <Mark>React</Mark>, and <Mark>Redux</Mark> for multiple digital agriculture applications.
          - Automate the deployment process within AWS environment using <Mark>Jenkins</Mark> and <Mark>Cloud Foundry</Mark>.

      - layout: left
        title: Bayer
        link: bayer.com
        sub_title: Geospatial Big Data Engineer 
        caption: 2018 - 2020
        quote: >
          Science for a better life
        description: | # this will include new lines to allow paragraphs
          - Design, build, and maintain APIs to process geospatial big data (satellite, lidar, and remote sensing data) to provide data value to data scientists and commercial communities (<Mark>Flask</Mark> + <Mark>Python</Mark> + <Mark>MVC</Mark>).
          - Leverage CICD to facilitate the development and deployment of various pipelines within AWS environment (<Mark>EC2</Mark>, <Mark>ECR</Mark>, <Mark>EMR</Mark>, <Mark>RDS</Mark>, <Mark>Data Pipeline</Mark>, <Mark>Lambda</Mark>, <Mark>Rundeck</Mark>, <Mark>Jenkins</Mark>).

      - layout: left
        title: Spatial Decision System
        sub_title: Software Developer (Internship)
        caption: 2016 and 2017 summer 
        description: | # this will include new lines to allow paragraphs
          - Develop <Mark>python</Mark> modules to simulate land development process (using <Mark>GDAL</Mark>, <Mark>Numpy</Mark>, <Mark>Pandas</Mark>, etc.).

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of North Carolina at Charlotte
        caption: 2010 - 2013
        sub_title: Geography and Urban Regional Analysis
        description: | # this will include new lines to allow paragraphs
          During my time as a Research Assistant at UNCC I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. 
          I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Achievements
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Gain the AWS Certified Solutions Architect (Associate), 2022 (https://www.credly.com/badges/62d77b97-51cb-4368-8f2a-3a99212b0811/linked_in?t=rg6yd3)
      - Won the First Place of 1904labs Mapathon (hackathon), 2020 
      -	Patent of Wetland Modeling and Prediction, May 28, 2015 (US20150347673.3)
      - Patent of Simulated Urban System and Applications, Apr 3, 2013 (China, CN102073645B)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Biking
      - Playing boardgames
      - Travelling

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
